### ISSUE TITLE
`TypeError: (intermediate value).getPreNextScripts(...).map is not a function` when doing a production build (dev works fine)

### ISSUE THREAD

**Issue by Neki** [nibtime/next-safe-middleware#23]
Hi,

Thanks for this project, this looks awesome and may solve a lot of issues I encountered when dealing with CSP with NextJS. You should probably advertise it more :)

After setting up the middleware according to the docs, I get the following error on all pages when doing a `yarn build`:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: (intermediate value).getPreNextScripts(...).map is not a function
    at Head.getPreNextScripts (<myproject>/node_modules/@next-safe/middleware/dist/document/index.js:10:24000)
    at Head.render (<myproject>/node_modules/next/dist/pages/_document.js:500:292)
    at Head.render (<myproject>/node_modules/@next-safe/middleware/dist/document/index.js:10:24414)
    at d (<myproject>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)
    at bb (<myproject>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (<myproject>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (<myproject>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToStaticMarkup (<myproject>/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:51:446)
    at renderToHTML (<myproject>/node_modules/next/dist/server/render.js:991:39)
    at async <myproject>/node_modules/next/dist/export/worker.js:253:36
```

`pages/_document.tsx` is:

```tsx
import { Html, Main, DocumentContext } from "next/document";
import NextSafeDocument, {
  provideComponents,
} from "@next-safe/middleware/dist/document";
import React from "react";

class MyDocument extends NextSafeDocument {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await NextSafeDocument.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    const { Head, NextScript } = provideComponents(this.props);
    return (
      <Html>
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

Removing the Head component does allow the build to work (but of course this makes the middleware much less useful).

On the other hand, the app works fine in dev with `yarn dev`. It's a Typescript app and no type errors are detected. I'm using version `    "@next-safe/middleware": "^0.5.2"` with `"next": "12.1.4"`.
I do have one `<Script>` component in the app, set to `lazyOnload`. Removing the script or changing the load strategy has no effect. 

Am I missing something? How can I investigate this issue? I'm happy to provide more information if needed.

**Comment by nibtime** [comment]
Hi @Neki,

thanks for the praise, your interest in the project, and for reporting this. Haven't gotten to advertise it yet, I first want to get it right and useful 😅.

Thanks for offering more investigation, but you already provided enough, I immediately knew this had to be some internal change from a new next version.

But if you try out this lib and provide insights in your use-cases and report bugs like this in the future that would be great! 

Too bad you encountered this error. Without the document drop-ins, all the strict CSP stuff won't work, which is the most valuable thing this lib offers.  And it only gets active in production mode, it is totally incompatible with the Next dev server by nature. You did everything right in configuration though.

**Good news is you simply can to downgrade next to `12.1.0` for now and it will work.**


At the bottom I also explained my motivation and use-cases for this lib and how it came to be, so you can decide better if it fits your CSP needs with Next as well.

### The Bug
The problem you are experiencing is due a change in `next/document` introduced between `12.1.0` and `12.1.4`: https://github.com/vercel/next.js/commit/79016b879f200c99cc3c3b69b2b84dee14b6615e#diff-5d810eb5cd68f6a6a3597e5472015f0c199e21d97cdabc9f7d5ac3fa85adc369R139-R166

They introduced a strategy `webworker` for `next/script` and to integrate it they extended `Head.getPreNextScripts` which returns now a Fragment with elements as children instead of an Array with elements, hence the "map is not a function".

I will account for this in `0.6.0` and also test it with the new webworker strategy. From my first impression, the design for the strict CSP stuff should work as is with the new webworker strategy as well once this type error is fixed. 

### Background of the lib
If you want to have a CSP as described in https://web.dev/strict-csp/ without any hassle for hybrid Next apps, this package is what you are looking for. I was creating the package mainly to scratch my own itch, and having the strict CSP stuff with proper reporting was crucial to me. 

Strict CSPs have a huge advantage that they always have the same structure for every site and retain their strong security even if you use custom inline scripts (which you always have to at some point for real sites, analytics, tag manager, etc.) so I wondered why nobody has taken this properly to the framework level so far and that's why I created this. But to be fair, to do it really properly you need middleware and Next 12 only came out 11/2021. 

So my sites and your sites can use the same package with completely different scripts, with an allowlist approach it would be vastly different and provide room for individual configuration errors per project + every single configuration change has the potential for regressions. And script errors with CSP are always very expensive, in enforce mode they almost certainly break a very important part of your app if not your whole app.

That's why support for report-only mode and easy setup of reporting was crucial to me. So far, I use the package on a new production site with Sentry reporting active. The `strictDynamic` middleware worked perfectly the last month, didn't receive a single violation and crash report. This sort of continuous e2e testing is very valuable I think it would be great if all experiences and problems could get ingested in this lib.

I extracted the configuration of the site into a gist for demonstration purposes some weeks ago: https://gist.github.com/nibtime/d366bccccb761431acda31a8c85a5de6

The lastest thing I am trying to get right is strict inline styles (`style-src`) for hybrid apps, which is trickier than I thought if you consider all aspects of it. But I think I got a pretty decent solution now. I got it to work for the CSS-in-JS framework stitches, which is my main use-case, that is already released in `0.5.2`. I also have a more general solution ready that accounts for style tags and style attributes used inside pages (Next uses those sometimes, e.g. for `ErrorComponent`) which I am going to release in `0.6.0.` alongside the fix. Also lot of other people seem to have those kind of problems: https://github.com/vercel/next.js/discussions/18451

**Comment by nibtime** [comment]
Hi @Neki 

I just released [`0.6.0`](https://github.com/nibtime/next-safe-middleware/releases/tag/%40next-safe%2Fmiddleware%400.6.0) on npm which includes the fix for Next `12.1.4`. 

The reason for this problem is actually a great new feature of `next/script` for running scripts in the background with webworkers (using partytown). I made sure this new strategy is supported with the strict-dynamic CSPs.

You can check out https://next-safe-middleware.vercel.app/ that's the e2e test app deployed to Vercel where I keep adding small test scenarios. 

Once I learned what makes sense in terms of quality and have some more reporting insights from my apps I will think about how to set up automation for e2e testing.

**Comment by Neki** [comment]
Thanks for the detailed explanations and quick fix :) 

In the meantime I went for a simple solution by disabling automatic static optimization globally, which allow me to add a CSP header on each response, but that's not good for performance, so I'll check out 0.6.0.

The part about the background of the lib is exactly why I tried this package: I need a strict CSP for a hybrid app with violation reports enabled, which can't be done with a meta tag in `<head>`. I was really surprised to see that there was no readily available solution, because that seems like a common enough requirement.

**Comment by nibtime** [comment]
Hi @Neki,

you're welcome :). Hope `0.6.0` is working for you. 

I was also surprised that there is no such solution. I think the core problem is, that there seems to be no real common ground about best practices on this atm and that has been preventing such a solution from happening.

So I did some advertising :) 

* https://github.com/vercel/next.js/issues/23993. 
* https://github.com/google/strict-csp/discussions/49

But promoting my lib is not the main goal. I've thrown it into the ring as a PoC to give an idea how a good solution for CSP stuff could look like. A native solution built into Next, where it gets all the testing, documentation, etc. would be much better then this lib. Hopefully, this happens at some point :)

**Comment by nibtime** [comment]
@all-contributors please add @neki for bug
