### ISSUE TITLE
Next.js 12.2  Nested Middleware is not allowed

### ISSUE THREAD

**Issue by malithmcr** [nibtime/next-safe-middleware#35]
I'm trying to use this package with next 12.2 but I keep getting:

error - Nested Middleware is not allowed, found:
pages/_middleware
Please move your code to a single file at /src/middleware instead.
Read More - https://nextjs.org/docs/messages/nested-middleware

Might be related to the latest release: https://nextjs.org/blog/next-12-2#middleware-stable

**Comment by nibtime** [comment]
You have to use `middleware.js` at the root of your Next.js project now instead of `pages/_middleware.js` with 12.2

I will update the e2e test app to Next 12.2 soon

**Comment by malithmcr** [comment]
Hey thanks, Already closed this issue because found out I've added underscore in front of the middleware in rooter folder :D

**Comment by nibtime** [comment]
@malithmcr 

The package also didn't work for Next 12.2 (`req.page` deprecated) :D. But I fixed it in #37 and released `0.8.0` to NPM 

It is important to match requests now, otherwise, middleware runs on absolutely everything, fonts, assets etc. There is a `chainMatch(isPageRequest)` now for that, its also in the updated README.
